#!/bin/sh

cwd=$(pwd)

inotifywait -m --timefmt '%d/%m/%y %H:%M' --format '%T %w %f' \
    -e close_write,moved_to --format %e/%f . |
while IFS=/ read -r events file; do
    if [ "$file" = "test" ]; then
        echo "\t- $file was backed up" >&2
    fi
done
    
